Repository 2024-tuk-graduation/Frontend, pull requests merged in 2024-06, with the labels that each got.

#83 [Feat/#70] 호스트 바꾸기 api 연동
  package.json
  src/assets/scss/components/_index.scss
  src/assets/scss/components/editor/Infobar/_entranceCode.scss
  src/assets/scss/components/modal/_editorModal.scss
  src/components/Editor/Chat/VideoChat.tsx
  src/components/Editor/Infobar/EditorInfobar.tsx
  src/components/Editor/Infobar/EntranceCode.tsx
  src/components/Editor/ParticipantsList.tsx
  src/components/index.ts
  src/components/modal/BaseModal.tsx
  src/components/modal/EditorModal.tsx
  src/components/modal/EntryModal.tsx
  src/hooks/services/mutations/useChangeHost.ts
  src/hooks/services/queries/useEditorRoomInfo.ts
  src/pages/Editor.tsx
  src/store/editorRoomInfoStore.ts
  src/store/modalStore.ts
  src/types/index.ts
  yarn.lock
Labels: FEAT

#84 feat : 그림 그리기 웹소켓 연동 성공
  src/components/Editor/Blank/ BlankCanvas.tsx
  src/components/Editor/Palatte/Palette.tsx
  src/components/Editor/Pdf/PdfView.tsx
  src/components/createRoom/EditorMode.tsx
  src/hooks/useCanvas.ts
Labels: FEAT

#88 [Fix/#87]
  src/components/Editor/Chat/VideoChat.tsx
Labels: FIX

#90 [Feat/#79] QandA 기능 구현
  package.json
  src/assets/images/chatIcon.svg
  src/assets/images/qna1.svg
  src/assets/images/qna2.svg
  src/assets/scss/components/editor/Chat/_videoChat.scss
  src/assets/scss/components/editor/_QandA.scss
  src/components/Editor/Chat/VideoChat.tsx
  src/components/Editor/Code/Compile.tsx
  src/components/Editor/QandA.tsx
  src/pages/Editor.tsx
  src/store/EditorMenuStore.ts
  yarn.lock
Labels: FEAT

#91 dasign : 에디터모드 모달창 버튼 css 수정
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/components/editor/Chat/_videoCAM.scss
  src/assets/scss/components/modal/_editorModal.scss
  src/assets/scss/pages/_editor.scss
  src/components/modal/BaseModal.tsx
  src/components/modal/EditorModal.tsx
Labels: DESIGN
