Repository 2024-tuk-graduation/Frontend, pull requests merged in 2024-04, with the labels that each got.

#37 Design/#34
  src/assets/images/cplusepluse.svg
  src/assets/images/javascript.svg
  src/assets/images/pdfFile.svg
  src/assets/images/python.svg
  src/assets/images/template/template1.png
  src/assets/images/template/template2.png
  src/assets/images/template/template3.png
  src/assets/images/template/template4.png
  src/assets/images/template/template5.png
  src/assets/images/template/template6.png
  src/assets/images/trash.svg
  src/assets/images/upload.svg
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/base/_common.scss
  src/assets/scss/base/_reset.scss
  src/assets/scss/components/_index.scss
  src/assets/scss/components/_navbar.scss
  src/assets/scss/components/createRoom/_blankScreenModeCreate.scss
  src/assets/scss/components/createRoom/_codeLanguage.scss
  src/assets/scss/components/createRoom/_codeModeCreate.scss
  src/assets/scss/components/createRoom/_editorModeButton.scss
  src/assets/scss/components/createRoom/_editorModeCreate.scss
  src/assets/scss/components/createRoom/_pdfModeCreate.scss
  src/assets/scss/pages/_createRoom.scss
  src/components/createRoom/BlankScreenModeCreate.tsx
  src/components/createRoom/BlankScreenModeSelect.tsx
  src/components/createRoom/CodeLanguage.tsx
  src/components/createRoom/CodeModeCreate.tsx
  src/components/createRoom/CodeModeSelect.tsx
  src/components/createRoom/EditorMode.tsx
  src/components/createRoom/EditorModeButton.tsx
  src/components/createRoom/PdfModeCreate.tsx
  src/components/createRoom/PdfModeSelect.tsx
  src/components/index.ts
  src/hooks/useFileUpload.ts
  src/pages/CreateRoom.tsx
  src/store/selectModeStore.ts
Labels: DESIGN, FEAT

#13 [Feat/#11] 회원가입 페이지 퍼블리싱
  src/assets/images/defaultProfile.svg
  src/assets/images/sign_bg.png
  src/assets/scss/base/_common.scss
  src/assets/scss/pages/_index.scss
  src/assets/scss/pages/_login.scss
  src/assets/scss/pages/_signUp.scss
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/store/loginFormState.ts
  src/store/store.ts
Labels: FEAT

#36 [Feat/#35] 로그인 및 회원가입 api 연동
  src/assets/images/default_profile.svg
  src/components/Editor/Code/CodeEditor.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  vite.config.ts
  yarn.lock
Labels: FEAT

#39 [Design/#38] 에디터페이지 ui 변경으로 전체적인 퍼블리싱 리펙토링
  src/assets/images/addFile.svg
  src/assets/images/record.svg
  src/assets/images/save.svg
  src/assets/images/time.svg
  src/assets/scss/abstracts/_mixins.scss
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/base/_common.scss
  src/assets/scss/components/_index.scss
  src/assets/scss/components/_navbar.scss
  src/assets/scss/components/editor/Code/_codeFileItem.scss
  src/assets/scss/components/editor/Infobar/_addFile.scss
  src/assets/scss/components/editor/Infobar/_editorInfobar.scss
  src/assets/scss/components/editor/Infobar/_entranceCode.scss
  src/assets/scss/components/editor/Infobar/_index.scss
  src/assets/scss/components/editor/Infobar/_record.scss
  src/assets/scss/components/editor/Infobar/_save.scss
  src/assets/scss/components/editor/Infobar/_time.scss
  src/assets/scss/components/editor/Personnel/_personnel.scss
  src/assets/scss/components/editor/_QandA.scss
  src/assets/scss/components/editor/_defaultMenubar.scss
  src/assets/scss/components/editor/_editorRoundButton.scss
  src/assets/scss/components/editor/_index.scss
  src/assets/scss/components/editor/_memo.scss
  src/assets/scss/components/editor/_modeEditor.scss
  src/assets/scss/components/editor/_palette.scss
  src/assets/scss/components/editor/_personMenubar.scss
  src/assets/scss/components/editor/_whiteBoard.scss
  src/assets/scss/pages/_editor.scss
  src/components/Editor/Code/CodeEditor.tsx
  src/components/Editor/Code/CodeFileItem.tsx
  src/components/Editor/Code/Compile.tsx
  src/components/Editor/DefaultMenubar.tsx
  src/components/Editor/Infobar/AddFile.tsx
  src/components/Editor/Infobar/EditorInfobar.tsx
  src/components/Editor/Infobar/EntranceCode.tsx
  src/components/Editor/Infobar/Record.tsx
  src/components/Editor/Infobar/Save.tsx
  src/components/Editor/Infobar/Time.tsx
  src/components/Editor/Memo.tsx
  src/components/Editor/ModeEditor.tsx
  src/components/Editor/Palette.tsx
  src/components/Editor/PersonMenubar.tsx
  src/components/Editor/Personnel/Personnel.tsx
  src/components/Editor/QandA.tsx
  src/components/Editor/TitleBar.tsx
  src/components/Editor/WhiteBoard.tsx
  src/components/Editor/index.ts
  src/components/Navbar.tsx
  src/components/index.ts
  src/pages/Editor.tsx
  src/store/EditorMenuStore.ts
  src/store/editorRoomInfoStore.ts
Labels: DESIGN, FEAT

#45 [feat/#44] 폰트 적용
  src/assets/font/SUITE-woff2/LICENSE
  src/assets/font/SUITE-woff2/SUITE-Bold.woff2
  src/assets/font/SUITE-woff2/SUITE-ExtraBold.woff2
  src/assets/font/SUITE-woff2/SUITE-Heavy.woff2
  src/assets/font/SUITE-woff2/SUITE-Light.woff2
  src/assets/font/SUITE-woff2/SUITE-Medium.woff2
  src/assets/font/SUITE-woff2/SUITE-Regular.woff2
  src/assets/font/SUITE-woff2/SUITE-SemiBold.woff2
  src/assets/font/SUITE-woff2/SUITE.css
  src/assets/font/index.ts
  src/assets/scss/abstracts/_mixins.scss
  src/assets/scss/base/_common.scss
  src/components/selectRoom/SelectButton.tsx
  src/pages/CreateRoom.tsx
  src/pages/Login.tsx
Labels: DESIGN

#49 [Feat/#42] 방 생성 페이지 api 연동
  package.json
  src/App.tsx
  src/assets/images/c.svg
  src/assets/images/cplusepluse.svg
  src/assets/scss/components/createRoom/_blankScreenModeCreate.scss
  src/assets/scss/components/createRoom/_codeLanguage.scss
  src/assets/scss/pages/_createRoom.scss
  src/components/Editor/Code/CodeEditor.tsx
  src/components/Editor/Infobar/EntranceCode.tsx
  src/components/Editor/ModeEditor.tsx
  src/components/Editor/Personnel/Personnel.tsx
  src/components/createRoom/BlankScreenModeCreate.tsx
  src/components/createRoom/CodeLanguage.tsx
  src/components/createRoom/CodeModeCreate.tsx
  src/components/createRoom/FileUpload.tsx
  src/components/createRoom/PdfModeCreate.tsx
  src/components/createRoom/SelectUpload.tsx
  src/components/modal/EntryModal.tsx
  src/components/selectRoom/SelectButton.tsx
  src/hooks/index.ts
  src/hooks/services/customApi.ts
  src/hooks/services/mutations/customMutation.ts
  src/hooks/services/mutations/useCreateRoom.ts
  src/hooks/services/mutations/useEntry.ts
  src/hooks/services/queries/useEditorRoomInfo.ts
  src/hooks/services/useFileUpload.ts
  src/hooks/useCreateFileUpload.ts
  src/hooks/useFileUpload.ts
  src/pages/CreateRoom.tsx
  src/pages/Editor.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/store/createRoomStore.ts
  src/store/editorRoomInfoStore.ts
  src/store/selectModeStore.ts
  src/types/Mode.ts
  yarn.lock
Labels: FEAT
